### ISSUE TITLE
GPS BN-880 compass heading

### ISSUE THREAD

**Issue by kusree** [lyusupov/SoftRF#25]
Do you have plan to read the SDA and SCL pin from BN-880 GPS as the aircraft heading?

**Comment by lyusupov** [comment]
No. Lot of work with little profit. Potential issues with EMI and calibration.
With standard equipment of a glider or powered airplane there is no need to have extra compass.

BN-880 was chosen because of 8-gen Ublox and active antenna. Mag, chip is a free bonus.

I will likely not object if someone will develop aside the support for this I2C compass. If he/she will succeed and if I will found this valuable for the project -  I may consider to help with integration.
