### ISSUE TITLE
AirConnect protocol

### ISSUE THREAD

**Issue by JuergenLeber** [lyusupov/SoftRF#30]
Just tried AirConnect with "Air Navigation Pro" app but didn't succeed. I defined AirConnect as active and server gets started. Port 2000 is working and delivering NMEA data. But I think the protocol is not fully correct. May I help here or are you already working on this? Not that we do double work.

**Comment by JuergenLeber** [comment]
I'll have a look into it, please assign to me!

**Comment by JuergenLeber** [comment]
Was a problem with a missing "\n". The AirConnect protocol waits for four digits and then starts sending the NMEA output if password is correct. Implemented in PR #34 .

**Comment by lyusupov** [comment]
Try out this commit: https://github.com/lyusupov/SoftRF/commit/c0038e10c2e84c34e787c2067237aaaabba2c7e8

It works for me:

![aconnect_1](https://user-images.githubusercontent.com/5849637/45864235-feea5100-bd81-11e8-9388-f97e1a8cc2d9.JPG)

<br>

![aconnect_2](https://user-images.githubusercontent.com/5849637/45864217-e9752700-bd81-11e8-8c20-7c46db9cd4d7.jpg)


And, please, double check that no any **CR**s or **LF**s after **PASS?** and **AOK** are actually in use in genuine AirConnect. Because I would prefer to see a better look in the monitor window.

**Comment by JuergenLeber** [comment]
In genuine AirConnect no CRs or LFs are used. It only sends "PASS?" and waits for either LF or exactly four bytes of data without LF and then sends "AOK" if password is/was correct. After that directly the NMEA data is sent. So I don't know if your version will work 100% as it doesn't count the four bytes but instead has a timeout. I'll try!

**Comment by lyusupov** [comment]
My opinion that this is an Air Navigation Pro's issue.
SkyDemon is smart enough - when it already sees NMEA sentences in the input stream - there is no need to enter pass codes anymore.
XCSoar does not care about handshake at all.

**I am definitely not going to break compatibility** with XCSoar, LK8000 and SeeYou as most of glider pilots are using them on daily basis, **just in order to make AirNav Pro users happy**.

**Comment by JuergenLeber** [comment]
I'll try with Air Nav Pro and most probably it's supposed to work with the timeout solution even if it's not the correct AirConnect protocol standard. So I can't tell you where the issue is exactly located. Let's find a solution to make all app's users happy.

**Comment by JuergenLeber** [comment]
Works with Air Nav Pro. But ANP still says "Bad GPS for navigation", probably something with GPRMC vs. GNRMC. But that's another problem.
