### ISSUE TITLE
GDL90 Ownship Geometric Altitude

### ISSUE THREAD

**Issue by maehtricks** [lyusupov/SoftRF#31]
First of all: thanks for your fantastic work.

I've noticed an issue with RC5 regarding GDL90 Ownship Geometric Altitude. With RC4 the altitude was shown correctly in SkyDemon, but with RC5 it's off.

GDL90 spec states that it has to be reported as relative to the WGS84 ellipsoid, with RC5 it looks like MSL alt is send.

- WebUI: 91m - correct alt
- XCSoar (FLARM): 138m - too high, looks like ellipsoidal height is send instead of MSL alt
- SkyDemon (GDL90): 130ft - too low, looks like MSL alt is send instead of ellipsoidal height

I'm using Prime MK2 Hardware.

**Comment by lyusupov** [comment]
Please, provide, being taken at earth surface level, screenshots (width <=800 pixels) of:
1) status page ;
2) settings page ;
3) 'monitor' window of XCSoar's device menu (in portrait mode) with at least one full second burst of GNSS NMEA sentences.

**Comment by maehtricks** [comment]
Alright, I did some testing this morning. My hardware is t22_v07.

I took screenshots from RC4 and RC5:

1. Status
2. Settings
3. SkyDemon (GDL90)
4. Avare external I/O plugin (GDL90)
5. XCSoar (NMEA)

### RC4
status
![rc4_01_status](https://user-images.githubusercontent.com/6266018/45415982-21dc7d00-b67f-11e8-8b52-3a59d8082b14.png)
settings
![rc4_02_settings](https://user-images.githubusercontent.com/6266018/45415983-22751380-b67f-11e8-8ed5-e7f6c3f991c3.png)
skydemon
![rc4_03_skydemon](https://user-images.githubusercontent.com/6266018/45415984-22751380-b67f-11e8-8d9d-9641947eb6d7.png)
avare
![rc4_04_avare](https://user-images.githubusercontent.com/6266018/45415985-22751380-b67f-11e8-900f-8b182ce79d04.png)
xcsoar
![rc4_05_xcsoar](https://user-images.githubusercontent.com/6266018/45415986-22751380-b67f-11e8-8916-1dea3b0fcc27.png)

### RC5
status
![rc5_01_status](https://user-images.githubusercontent.com/6266018/45415987-230daa00-b67f-11e8-96b3-a4f62ae90a4d.png)
settings
![rc5_02_settings](https://user-images.githubusercontent.com/6266018/45415988-230daa00-b67f-11e8-893a-e1bf7f3a2f1a.png)
skydemon
![rc5_03_skydemon](https://user-images.githubusercontent.com/6266018/45415989-230daa00-b67f-11e8-9ff8-a1d4fb2c62e1.png)
avare
![rc5_04_avare](https://user-images.githubusercontent.com/6266018/45415990-230daa00-b67f-11e8-8527-0336c749b95b.png)
xcsoar
![rc5_05_xcsoar](https://user-images.githubusercontent.com/6266018/45415992-23a64080-b67f-11e8-8514-490fd4aa3d43.png)

**Comment by lyusupov** [comment]
Ok. Thank you! 

**You report is a mix of two issues**:
1) in both RC4 and RC5 there was a minor bug in GDL90 geometric altitude reporting. Fixed in https://github.com/lyusupov/SoftRF/commit/cf5d37eebaf47fbcfb1fa40dc7fb37fa9d81b3d0
2) you have so-called ["heavy counterfeit" GNSS module](http://ttgobbs.com/viewthread.php?tid=17131&rpid=155152&ordertype=0&page=2#pid155152) soldered into your T-Beam.
 
**Indicators of that**:

![issue31-1](https://user-images.githubusercontent.com/5849637/45419110-00838d00-b68f-11e8-8bf9-278226d4b53a.png)

and

![issue31-2](https://user-images.githubusercontent.com/5849637/45419127-0c6f4f00-b68f-11e8-8e08-774d0009a051.png)

Issue with these GNSS modules is that they always report "0.0" as geoidal separation value.
It was recently first discovered and reported by [Pawel Jalocha](https://github.com/pjalocha) .
 
Most of modern GNSS ICs are reporting AMSL altitude in their NMEA $GxGGA sentence: http://aprs.gids.nl/nmea/#gga
Followed by "geoidal separation value" - hight difference between WGS84 ellipsoid and EGM96 geoid.

We don't know for sure what is the "altitude" value reported by this "heavy counterfeit" GNSS chip, but it looks like an altitude relative to WGS84 ellipsoid.
Old GPSes (prior to year 2000 or so) were also reporting WGS84 altitude, **but they were suppling EMPTY geo separation field**.

This is an example for your latitude and longitude taken from [online calculator](https://www.unavco.org/software/geodetic-utilities/geoid-height-calculator/geoid-height-calculator.html):
```

Your Input Coordinates and GPS Height: 

Latitude = 49.63° N = 49° 37' 48" N 
Longitude = 8.61° E = 8° 36' 36" E 
GPS ellipsoidal height = 142.0 (meters) 
Geoid height = 48.035 (meters) 
Orthometric height (height above EGM96 geoid which approximates mean sea level) = 93.965 (meters) 


(note: orthometric height = GPS ellipsoidal height - geoid height) 
```

**RC5 has a workaround implemented against these "heavy counterfeit" ICs**. The algorithm of EGM96 based altitude adjustment was borrowed from XCSoar. So reported SoftRF RC5 WebUI AMSL altitude should be the same or very close to the value taken from XCSoar's navbox.
Due flash memory space constraints, geo separation value is avaraged over 2 degrees lat/lon "square" earth surface. Not perfect, but still acceptable for most aviation applications.

**Comment by lyusupov** [comment]
I am curious:
1) why are you using 868.2 MHz for P3I ?

![issue31-3](https://user-images.githubusercontent.com/5849637/45421051-835b1680-b694-11e8-8518-6933c0ec8748.jpg)

have you read this ? : https://github.com/lyusupov/SoftRF/wiki/Settings

2) Which way did get your RC5? Custom built?

![issue31-4](https://user-images.githubusercontent.com/5849637/45421117-be5d4a00-b694-11e8-8440-d2d3c09e024d.jpg)

It should report more that 4000000 bytes on officially released RC5 running on T-Beam board.

**Comment by maehtricks** [comment]
Cool, thank you for the fix and the explanations. Is there a special setting to activate the altitude workaround in XCSoar? Right now it's showing the same alt (GPS ellipsoidal) in the alt gps box as in NMEA sentences with no correction.

1. I'm using the legacy protocol normally... so this was some weird setting from last night's testing.

2. I was experimenting as well with the GDL90 alt with my own build... but the screenshots were taken from the same source as your's. But you're right, with your build it shows more than 4000000 bytes. I'll have to check what's wrong with my setup.

**Comment by maehtricks** [comment]
Checked this... XCSoar's correction just kicks in if it's not a valid double value. Since 0.0 is valid, no correction will be performed. I saw this in the code and tested it by playing back a modified nmea caputure. If I remove 0.0 the proper altitude is shown.

**Comment by maehtricks** [comment]
Checked GDL90 Ownship Geometric Altitude report successfully with SkyDemon + Avare.

Thank you very much.

**Comment by lyusupov** [comment]
> XCSoar's correction just kicks in if it's not a valid double value. Since 0.0 is valid, no correction will be performed. I saw this in the code and tested it by playing back a modified nmea caputure. If I remove 0.0 the proper altitude is shown.

**Comment by maehtricks** [comment]
> 
> 
> @maehtricks
> 
> > XCSoar's correction just kicks in if it's not a valid double value. Since 0.0 is valid, no correction will be performed. I saw this in the code and tested it by playing back a modified nmea caputure. If I remove 0.0 the proper altitude is shown.
> 
> Try out this commit: [0ef8557](https://github.com/lyusupov/SoftRF/commit/0ef855703d8b2dc505cd97a5cafa68a85c581ebf)

Works perfect. Thank you again :)

![grafik](https://user-images.githubusercontent.com/6266018/45501862-b7146a00-b782-11e8-866f-da6b63ddeff0.png)

**Comment by lyusupov** [comment]
@maehtricks

Ok. Good !

Could you, please, take one more screenshot of NMEA sentences in XCSoar's "monitor" window  (<=800px) ?
 I need to take a look at it.

**Comment by maehtricks** [comment]
Sorry for the delay... had some hardware issues. But here we go with BMP280 attached :) 
![screenshot_2018-09-15-11-27-35-02](https://user-images.githubusercontent.com/6266018/45585818-64a28d00-b8eb-11e8-9fb2-407c785778a8.jpeg)
![screenshot_2018-09-15-13-30-38-01](https://user-images.githubusercontent.com/6266018/45585852-ff02d080-b8eb-11e8-9437-3a47b9329454.jpeg)

**Comment by lyusupov** [comment]
@maehtricks:

Thank you!

I had to make sure that time/lat/lon of re-generated GGA sentence have same or close values & precision (digits after decimal point) as the parameters of pass-through RMC sentence.

![issue31-7](https://user-images.githubusercontent.com/5849637/45606467-faeec400-ba4d-11e8-8ee9-677c5ffad263.jpg)

**Comment by lyusupov** [comment]
Although GDL90 spec states that altitude has to be reported as relative to the WGS84 ellipsoid,
most of EFBs and portable ADS-B devices are reporting MSL altitude.
See this info for details: https://github.com/cyoung/stratux/pull/749
SkyDemon seems to be the only exception (that follows the specs).

I am going to revert my previous change soon.
I will sacrifice SkyDemon's altitude accuracy in favour of all other EFBs accuracy.

**Comment by maehtricks** [comment]
Hm, what do you think about adding it as option to be compatible to almost all EFBs on the market?

**Comment by lyusupov** [comment]
No sense to add the GDL90 menu option for the sake of SkyDemon only.
Users of SkyDemon can use NMEA TCP ("AirConnect") instead.

Alternatively, you can push SD team to use the MSL, like all other EFBs do.

**Comment by ragflyer** [comment]
**Summary for other Skydemon users:**
In SoftRF settings set 'NMEA output' to 'TCP', then in SD settings menu -> Third party devices -> FLARM devices -> FLARM with Air COnnect to 'on', leave the key as is. Altitude should now be shown correctly.
