### ISSUE TITLE
Feature: Configurable device name

### ISSUE THREAD

**Issue by bruceme** [lyusupov/SoftRF#47]
As a user, I'd like to be able to give my device a custom name.  That way I can tell it apart from other devices at a busy airfield without memorize it's hex identification.

Ideally it would be configured on the setup page and used as the bluetooth and wifi device name.

Format:  {DeviceName}-{DeviceID}

![img_20190216_215621](https://user-images.githubusercontent.com/1963589/52908170-e5b4d600-3235-11e9-9ce7-2c0bc94058db.png)
![img_20190216_215533](https://user-images.githubusercontent.com/1963589/52908171-e5b4d600-3235-11e9-975d-c40b1737ad2b.png)

**Comment by lyusupov** [comment]
Current naming scheme is not going to be changed.

1) On ESP32, with "fuses", user is able to alter Device id onto an ICAO address or (decimal) registration number.
This option has to be used with caution, because the fuses are one time programmable (OTP) only.

2) A lot of current SoftRF users are actually managing fleet of gliders in thier clubs. SoftRF firmware is open source code. It is typically not a big deal for the user to alter his(her) local copy of code and build a custom firmware, appropriate for a particular fleet.

**Resolution**: will not fix.
