### ISSUE TITLE
EEPROM magic mismatch!

### ISSUE THREAD

**Issue by zodiac-maniac** [lyusupov/SoftRF#69]
## Hardware

- [x]   Prime Mark II
- [x]   Standalone
- [ ]   UAV
- [ ]   Raspberry Edition
- [ ]   UAT module
- [ ]   SkyView
- [ ]   Flight Recorder

< photo of your hardware > (**required**)

## Firmware version
softRF Firmware v1.0 RC6+
<  screenshot of WebUI status page > (**required**)
Impossible
## Firmware settings
nothing special
<  screenshot of WebUI settings page > (**required**)
Impossible
## Describe the bug (or ask a question)
The t-beam Version 20190612 creates a WiFi spot.
It is possible to connect to softRF WiFi but the 192.168.1.1 is not working. Seems that a Gateway/Server does not work.
The difference to other t-beams is the magic mismatch report and I guess thats why softRF does not run. Is it possible to "repair" the eeprom?
When powering up the t-beam by USB Power and reading the serial port with serial port utility it says:
Reset reason: 0

POWERON_RESET

Free heap size: 202160

Vbat power on reset

Warning! EEPROM magic mismatch! Loading defaults...

SX1276 RFIC is detected.

WARNING! Barometric pressure sensor is NOT detected.

INFO: TTGO T-Beam GPS module (rev. 08) is detected.

Flash memory ID: EF4016

INFO: GNSS module HW version: 00040007

INFO: GNSS module FW version: 7.03 (45969)

Hostname: SoftRF-d44404

Wait for WiFi connection.

....................

Can not connect to WiFi station. Go into AP mode.

Setting soft-AP configuration ... Ready

Setting soft-AP ... Ready

IP address: 192.168.1.1

UDP server has started at port: 12389

HTTP server has started at port: 80

After that it shows the data of the GPS Module.
## Expected behavior
Normal softRF behavior...

**Comment by lyusupov** [comment]
There is **NO EEPROM** in ESP32.
It is emulated by SPI flash memory area (address and size are specified in partition table)

EEPROM magic mismatch! Loading defaults.. - **is just a warning** .
It indicates that flash memory area assigned for EEPROM emulation is not initialized yet.
It is Ok because factory (or user) pre-installed firmware does not contain definitions for this memory region.

It will become initialized normally when a user will make very first 'Save and restart' operation in 'Settings' menu.
