### ISSUE TITLE
ADSB mavlink packets

### ISSUE THREAD

**Issue by geofrancis** [lyusupov/SoftRF#9]
ardupilot can now send adsb packets down via the pixhawks telemetry connection to mission planner on the ground, as far as i know the pingRX is the only system to use it, if your SoftRF uav edition could send down adsb packet like the ping rx then you could get the FLARM data on mission planner.

**Comment by lyusupov** [comment]
SoftRF **has** support for MAVLINK 1.0's  **MAVLINK_MSG_ID_ADSB_VEHICLE** message
for a long term, since [this commit](https://github.com/lyusupov/SoftRF/commit/a5d8f955cc47734977963b338c313a10aadc65c1) .

An exampe on how to use int with the **Mission Planner** had been given here: https://github.com/lyusupov/SoftRF/wiki/UAV-Edition
